#DTA250 - Fall 2023
#JJ

# keys ----
# Keys are variables that are used to match observations in different data
# frames. A key can be a single variable or a combination of variables.

## Prerequisites ----

#TODO
# load the tidyverse package
library(tidyverse)

#TODO
# load the nycflights13 package
library(nycflights13)

## Primary and foreign keys ----
# Every join involves a pair of keys: a primary key and a foreign key.

### Primary keys ----
# A primary key is a variable or a set of variables that uniquely identifies
# each observation in a data frame.
# When more than one variable is used to uniquely identify each observation,
# the combination of these variables is called a composite key.

#TODO
# load the airlines dataset using the data() function
data(airlines)

# Notice the carrier column in the airlines dataset. This column contains the
# two-letter carrier codes for each airline. These codes are the primary key
# for the airlines dataset.

#TODO
# load the airports dataset using the data() function
data(airports)

# Notice the faa column in the airports dataset. This column contains the
# three-letter FAA codes for each airport. These codes are the primary key
# for the airports dataset.

#TODO
# load the planes dataset using the data() function
data(planes)

# Notice the tailnum column in the planes dataset. This column contains the
# tail numbers for each plane. These codes are the primary key for the planes

#TODO
# load the weather dataset using the data() function
data(weather)

# Notice the origin and time_hour columns in the weather dataset. These columns
# are the composite key for the weather dataset.

## Foreign keys ----
# A foreign key is a variable or a set of variables that uniquely identifies
# each observation in another data frame.

#TODO
# load the flights dataset using the data() function
data(flights)

# Notice the carrier, origin, dest, and tailnum columns in the flights dataset.
# These columns are the foreign keys for the flights dataset.
# The carrier column is a foreign key for the airlines dataset.
# The origin and dest columns are foreign keys for the airports dataset.
# The origin and time_hour columns are foreign keys for the weather dataset.

## Checking Primary Keys ----

# We can use the count() and filter() functions to check if a variable or a set
# of variables is a primary key.

#TODO
# Check if the tailnum column in the planes dataset is a primary key
# Use the count() and filter() functions
# The count() function will count the number of observations in each group
# The filter() function will filter the rows based on a condition
# The condition is that the number of observations in each group should not be 
# more than 1
# If the condition is true, then the tailnum column is a primary key
# If the condition is false, then the tailnum column is not a primary key
planes |>
  count(tailnum) |>
  filter(n > 1)

#TODO
# Can you check whether the origin and time_hour columns in the weather dataset
# are a primary key?
# Use the count() and filter() functions
weather |>
  count(origin, time_hour) |>
  filter(n > 1) 

# You also need to check if there are any missing values in the primary key
# columns. If there are missing values, then that row should be removed from
# the data frame. It is not considered an observation.

#TODO
# Check if there are any missing values in the tailnum column in the planes
# dataset
# Use the filter() and is.na() function
planes |>
  filter(is.na(tailnum))

#TODO
# Check if there are any missing values in the origin and time_hour columns in
# the weather dataset
# Use the filter() and is.na() function
# You also need the | operator to combine the two conditions
weather |>
  filter(is.na(origin) | is.na(time_hour))

## Surrogate keys ----

#TODO
# Can you use the flight column in the flights dataset as a primary key?
# Use the count() and filter() functions
flights |>
  count(flight) |>
  filter(n > 1)

#TODO
# Can you use the flight column along with the time_hour and carrier columns in
# the flights dataset as a primary key?
# Use the count() and filter() functions
flights |>
  count(flight, time_hour, carrier) |>
  filter(n > 1)

# It is certainly a good start to use these three columns as a primary key.
# However, it is not a good idea, and it might be confusing.

# This can be solved by creating a surrogate key. A surrogate key is a variable
# that uniquely identifies each observation in a data frame. The difference
# between a surrogate key and a primary key is that a surrogate key is not part
# of the original data. It is generated by the data analyst.

#TODO
# Create a surrogate key for the flights dataset
# Use the mutate() and row_number() functions
# The row_number() function will create a sequence of numbers from 1 to the
# number of observations in the data frame
# Call your new column id
flights <- flights |>
  mutate(id = row_number())